# Generated by Django 6.0.6 on 2026-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/cover_images/'),
        ),
    ]
